name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose
    - name: Run fmt check
      run: cargo fmt --all -- --check
    - name: Run clippy check
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
